thermal: max31760_fan: Fix unused result warning
../drivers/thermal/qcom/max31760_fan.c:331:3: error: ignoring return
value of function declared with 'warn_unused_result' attribute
[-Werror,-Wunused-result]
                (pdata->vdd_reg);
                ^~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~

Change-Id: I06fb07da60cb765e4daf98c38afdb97690491c6f