lahaina-qgki_defconfig: Enable all configs required by kernel FCM 6 This fulfills the necessary kernel requirements for kernel FCM 6 and fixes the following build warning:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_XFRM_MIGRATE
    Missing config CONFIG_HAVE_MOVE_PMD
    Missing config CONFIG_HAVE_MOVE_PUD
    Missing config CONFIG_USERFAULTFD