sched/idle: Include pelt header for update_idle_rq_clock_pelt()
This fixes the following compilation error:

../kernel/sched/idle.c:407:2: error: call to undeclared function 'update_idle_rq_clock_pelt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  407 |         update_idle_rq_clock_pelt(rq);
      |         ^

Fixes: a0950252106e3 ("sched/fair: Fix pelt clock sync when entering idle")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>